name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - accessible-pygments=0.0.4
  - alabaster=0.7.13
  - anyio=4.0.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - conda=23.9.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.9.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.4
  - dataclasses=0.8
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.17.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fmt=10.1.1
  - fqdn=1.5.1
  - gitdb=4.0.11
  - gitpython=3.1.40
  - greenlet=3.0.0
  - icu=73.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - json5=0.9.14
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-book=0.15.1
  - jupyter-cache=0.6.1
  - jupyter-lsp=2.2.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_core=5.4.0
  - jupyter_events=0.8.0
  - jupyter_server=2.8.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab-git=0.41.0
  - jupyterlab-spellchecker=0.8.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - krb5=1.21.2
  - latexcodec=2.0.1
  - libarchive=3.7.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libmamba=1.5.2
  - libmambapy=1.5.2
  - libnghttp2=1.52.0
  - libopenblas=0.3.24
  - libsodium=1.0.18
  - libsolv=0.7.25
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - llvm-openmp=17.0.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mistune=3.0.1
  - myst-nb=0.17.2
  - myst-parser=0.18.1
  - nbclient=0.7.4
  - nbconvert=7.9.2
  - nbconvert-core=7.9.2
  - nbconvert-pandoc=7.9.2
  - nbdime=3.2.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.0.0
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - pluggy=1.3.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pycosat=0.6.6
  - pycparser=2.21
  - pydata-sphinx-theme=0.14.1
  - pygments=2.16.1
  - pyobjc-core=10.0
  - pyobjc-framework-cocoa=10.0
  - pyopenssl=23.2.0
  - pyppeteer=1.0.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python.app=3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.39
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.1
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - smmap=5.0.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinx-book-theme=1.0.1
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.3.0
  - sphinx-external-toc=0.3.1
  - sphinx-jupyterbook-latex=0.5.2
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.2.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-bibtex=2.5.0
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - sqlalchemy=2.0.22
  - sqlite=3.43.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.11.2
  - truststore=0.8.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - uri-template=1.3.0
  - urllib3=1.26.18
  - wcwidth=0.2.8
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - websockets=10.4
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.21.0
  - zstd=1.5.5
  - pip:
      - aiofiles==22.1.0
      - aiosqlite==0.19.0
      - annotated-types==0.6.0
      - cachetools==5.3.1
      - dill==0.3.7
      - fica==0.3.1
      - google-api-core==2.12.0
      - google-api-python-client==2.104.0
      - google-auth==2.23.3
      - google-auth-httplib2==0.1.1
      - google-auth-oauthlib==1.1.0
      - googleapis-common-protos==1.61.0
      - httplib2==0.22.0
      - ipython-genutils==0.2.0
      - jupyter-client==7.4.9
      - jupyter-server-fileid==0.9.0
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.6
      - jupytext==1.15.2
      - nbclassic==1.0.0
      - notebook==6.5.6
      - oauthlib==3.2.2
      - otter-grader==4.3.1
      - playwright==1.13.0
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyee==8.2.2
      - pyparsing==3.1.1
      - python-on-whales==0.65.0
      - pyzmq==24.0.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - toml==0.10.2
      - typer==0.9.0
      - uritemplate==4.1.1
      - wrapt==1.15.0
      - y-py==0.6.2
      - ypy-websocket==0.8.4
